SUBROUTINE PTSWAP(Q,SENDER)
  USE VGWM
  USE VGWMC
  IMPLICIT NONE
  INCLUDE "mpif.h"
  INTEGER :: I,NODE,EXCH,ISTAT(MPI_STATUS_SIZE),ierr
  DOUBLE PRECISION :: Q(N3ATOM),CROE,LNP(PTSIZE+10),SDATA(PTSIZE+10),RNUM,W
  LOGICAL :: SENDER

  NODE=mynode
 
  IF(SENDER) THEN
     CALL VGWCQNCH(Q,LNP(1:ASIZE+1),0)
     CALL MPI_RECV(SDATA(1:PTSIZE+10),PTSIZE+10,MPI_DOUBLE_PRECISION,NODE+1,5,MPI_COMM_WORLD,ISTAT,ierr)  
     CALL RANDOM_NUMBER(RNUM)
     NSWPATT(2)=NSWPATT(2)+1
     W=EXP(LNP(ASIZE)+SDATA(ASIZE)-LNP(ASIZE+1)-SDATA(ASIZE+1))                  ! Weight
     IF(W.GT.RNUM) THEN
        NSWAPS(2)=NSWAPS(2)+1
        EXCH=1
        CALL MPI_SEND(EXCH,1,MPI_INTEGER,NODE+1,6,MPI_COMM_WORLD,ierr)
        LNP(ASIZE+2:PTSIZE)=Q(1:N3ATOM)
        LNP(PTSIZE+2)=STPLEN
        LNP(PTSIZE+3)=NACC
        LNP(PTSIZE+4)=NTACCP
        LNP(PTSIZE+5)=NTRANS
        STPLEN=SDATA(PTSIZE+2)
        NACC=INT(SDATA(PTSIZE+3))
        NTACCP=INT(SDATA(PTSIZE+4))
        NTRANS=INT(SDATA(PTSIZE+5))      
        IF(CHNGV) THEN
           LNP(PTSIZE+1)=BL
           BL=SDATA(PTSIZE+1)
           BL2=BL/2.0D0
           VCURR=BL**3
           LNP(PTSIZE+6)=VSLEN
           LNP(PTSIZE+7)=NVACC
           LNP(PTSIZE+8)=NVACCT
           LNP(PTSIZE+9)=NVSTEP
           VSLEN=SDATA(PTSIZE+6)
           NVACC=INT(SDATA(PTSIZE+7))
           NVACCT=INT(SDATA(PTSIZE+8))
           NVSTEP=INT(SDATA(PTSIZE+9))
        ENDIF 
        CALL MPI_SEND(LNP(1:PTSIZE+10),PTSIZE+10,MPI_DOUBLE_PRECISION,NODE+1,7,MPI_COMM_WORLD,ierr)
        ZCURR(1:ASIZE)=SDATA(1:ASIZE)
        Q(1:N3ATOM)=SDATA(ASIZE+2:PTSIZE)
     ELSE
        EXCH=0
        CALL MPI_SEND(EXCH,1,MPI_INTEGER,NODE+1,6,MPI_COMM_WORLD,ierr)
     ENDIF
  ELSE
     CALL VGWCQNCH(Q,LNP(1:ASIZE+1),1)
     LNP(ASIZE+2:PTSIZE)=Q(1:N3ATOM)
     LNP(PTSIZE+1)=BL
     LNP(PTSIZE+2)=STPLEN
     LNP(PTSIZE+3)=NACC
     LNP(PTSIZE+4)=NTACCP
     LNP(PTSIZE+5)=NTRANS
     IF(CHNGV) THEN
       LNP(PTSIZE+6)=VSLEN
       LNP(PTSIZE+7)=NVACC
       LNP(PTSIZE+8)=NVACCT
       LNP(PTSIZE+9)=NVSTEP
     ENDIF
     CALL MPI_SEND(LNP(1:PTSIZE+10),PTSIZE+10,MPI_DOUBLE_PRECISION,NODE-1,5,MPI_COMM_WORLD,ierr)
     CALL MPI_RECV(EXCH,1,MPI_INTEGER,NODE-1,6,MPI_COMM_WORLD,ISTAT,ierr)
     NSWPATT(1)=NSWPATT(1)+1
     IF(EXCH.EQ.1) THEN
        CALL MPI_RECV(LNP(1:PTSIZE+10),PTSIZE+10,MPI_DOUBLE_PRECISION,NODE-1,7,MPI_COMM_WORLD,ISTAT,ierr)
        ZCURR(1:ASIZE)=LNP(1:ASIZE)
        Q(1:N3ATOM)=LNP(ASIZE+2:PTSIZE)
        STPLEN=LNP(PTSIZE+2)
        NACC=INT(LNP(PTSIZE+3))
        NTACCP=INT(LNP(PTSIZE+4))
        NTRANS=INT(LNP(PTSIZE+5))
        IF(CHNGV) THEN
           BL=LNP(PTSIZE+1)
           BL2=BL/2.0D0         
           VCURR=BL**3
           VSLEN=LNP(PTSIZE+6)
           NVACC=INT(LNP(PTSIZE+7))
           NVACCT=INT(LNP(PTSIZE+8))
           NVSTEP=INT(LNP(PTSIZE+9))
        ENDIF         
        NSWAPS(1)=NSWAPS(1)+1
     ENDIF
  ENDIF
  
  ROECURR=ZCURR(ASIZE)

  CALL VGWFUPDATE(Q)  

END SUBROUTINE PTSWAP

SUBROUTINE ATTSWAP(Q,TFLAG)
  USE VGWM
  USE VGWMC
  IMPLICIT NONE
  INCLUDE "mpif.h"
  INTEGER ::I
  INTEGER, SAVE :: STATUS(MPI_STATUS_SIZE,100),REQT(100),TSTAT(MPI_STATUS_SIZE),RTMP,VTMP
  INTEGER, SAVE :: REQ(100),REQV(100),ierr
  DOUBLE PRECISION :: Q(N3ATOM)
  LOGICAL :: TFLAG
  LOGICAL, SAVE :: SENDNR,VSENDNR

  IF(PTINIT) THEN
     IF(mynode.GT.0) CALL MPI_IRECV(1,1,MPI_INTEGER,0,1,MPI_COMM_WORLD,REQ(1),ierr)
     TFLAG=.FALSE.
     SENDNR=.TRUE.
     VSENDNR=.TRUE.
     PTINIT=.FALSE.
  ENDIF

  IF(NVOUT.GT.0) THEN
     IF(mynode.EQ.0) THEN
        IF(MOD(NTOTAL,NVOUT).EQ.0) THEN
           DO I=1,NREPS-1
              CALL MPI_ISEND(2,1,MPI_INTEGER,I,2,MPI_COMM_WORLD,REQV(I),ierr)   ! Send terminate signal
           ENDDO
           CALL MPI_WAITALL(NREPS-1,REQV,STATUS,ierr)
           WRITE(VOLFIND,"(I15,F15.5)") NTOTAL,BL
           CALL FLUSH(VOLFIND)
        ENDIF
     ELSE
        IF(VSENDNR) THEN
           CALL MPI_IRECV(VTMP,1,MPI_INTEGER,0,2,MPI_COMM_WORLD,REQ(2),ierr)      
           VSENDNR=.FALSE.
        ENDIF
        
        CALL MPI_TEST(REQ(2),VSENDNR,TSTAT,ierr)
     
        IF(VSENDNR) THEN
           WRITE(VOLFIND,"(I15,F15.5)") NTOTAL,BL   ! Output current volume of node to file
           CALL FLUSH(VOLFIND)
        ENDIF
     ENDIF
  ENDIF
     
  IF(mynode.EQ.0) THEN
     IF(NTOTAL.GE.NSTEP) THEN
        DO I=1,NREPS-1
           CALL MPI_ISEND(1,1,MPI_INTEGER,I,1,MPI_COMM_WORLD,REQT(I),ierr)             ! Send terminate signal
        ENDDO
        CALL MPI_WAITALL(NREPS-1,REQT,STATUS,ierr)
        TFLAG=.TRUE.
     ENDIF
  ELSE  
     CALL MPI_TEST(REQ(1),TFLAG,TSTAT,ierr)  
    
     IF((CSTEP(1).GE.SWPINT).AND.(.NOT.TFLAG)) THEN      
     
        IF(SENDNR) THEN
           CALL MPI_IRECV(RTMP,1,MPI_INTEGER,mynode-1,3,MPI_COMM_WORLD,REQ(3),ierr)
           SENDNR=.FALSE.
        ENDIF
        
        CALL MPI_TEST(REQ(3),SENDNR,TSTAT,ierr)
        
        IF(SENDNR) THEN
           CALL PTSWAP(Q,.FALSE.)
           CSTEP(1)=0
        ENDIF
     ENDIF
  ENDIF
     
  IF((CSTEP(2).GE.SWPINT).AND.(.NOT.TFLAG).AND.(mynode.LT.(NREPS-1))) THEN
     CALL MPI_ISEND(3,1,MPI_INTEGER,mynode+1,3,MPI_COMM_WORLD,REQ(4),ierr)  
     CALL MPI_WAIT(REQ(4),TSTAT,ierr)
     CALL PTSWAP(Q,.TRUE.)
     CSTEP(2)=0
  ENDIF

END SUBROUTINE ATTSWAP
